name: easytp
version: 1
handle:
- hostaccess: if(path ~ "^/App") deny "all"
- hostaccess: if(path ~ "^/Libs") deny "all"
- hostaccess: if(path ~ "^/config.yaml") deny "all"
- hostaccess: if(path ~ "^/sae_app_wizard.xml") deny "all"
- rewrite: if(!is_dir() && !is_file() && path~"^(.*)$") goto "index.php/$1"
